/**
 * session_key is generated by MySQL UUID() (char(36)).
 * We treat it as a public identifier (NOT a secret) used by clients to subscribe
 * to realtime rooms (sessionKey:<uuid>). Validation is format-only.
 */

const UUID_RE = /^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;

export function verifyClientSessionKey(sessionKey: string): boolean {
  const s = String(sessionKey ?? "").trim();
  if (!s) return false;
  return UUID_RE.test(s);
}
