CREATE TABLE IF NOT EXISTS payroll_profiles (
  payroll_profile_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  branch_id BIGINT UNSIGNED NOT NULL,
  staff_id BIGINT UNSIGNED NOT NULL,
  salary_mode VARCHAR(20) NOT NULL DEFAULT 'MONTHLY',
  base_monthly_amount BIGINT NOT NULL DEFAULT 0,
  hourly_rate_amount BIGINT NOT NULL DEFAULT 0,
  shift_rate_morning BIGINT NOT NULL DEFAULT 0,
  shift_rate_evening BIGINT NOT NULL DEFAULT 0,
  late_penalty_per_minute BIGINT NOT NULL DEFAULT 0,
  early_leave_penalty_per_minute BIGINT NOT NULL DEFAULT 0,
  absence_penalty_amount BIGINT NOT NULL DEFAULT 0,
  is_active TINYINT(1) NOT NULL DEFAULT 1,
  note VARCHAR(1000) DEFAULT NULL,
  version INT NOT NULL DEFAULT 1,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (payroll_profile_id),
  UNIQUE KEY uq_payroll_profile_staff_branch (branch_id, staff_id),
  KEY idx_payroll_profile_branch_active (branch_id, is_active),
  CONSTRAINT fk_payroll_profile_branch FOREIGN KEY (branch_id) REFERENCES branches(branch_id),
  CONSTRAINT fk_payroll_profile_staff FOREIGN KEY (staff_id) REFERENCES staff_users(staff_id),
  CONSTRAINT ck_payroll_salary_mode CHECK (salary_mode IN ('MONTHLY', 'HOURLY', 'SHIFT')),
  CONSTRAINT ck_payroll_base_monthly_amount CHECK (base_monthly_amount >= 0),
  CONSTRAINT ck_payroll_hourly_rate_amount CHECK (hourly_rate_amount >= 0),
  CONSTRAINT ck_payroll_shift_rate_morning CHECK (shift_rate_morning >= 0),
  CONSTRAINT ck_payroll_shift_rate_evening CHECK (shift_rate_evening >= 0),
  CONSTRAINT ck_payroll_late_penalty_per_minute CHECK (late_penalty_per_minute >= 0),
  CONSTRAINT ck_payroll_early_leave_penalty_per_minute CHECK (early_leave_penalty_per_minute >= 0),
  CONSTRAINT ck_payroll_absence_penalty_amount CHECK (absence_penalty_amount >= 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS payroll_bonus_entries (
  payroll_bonus_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  branch_id BIGINT UNSIGNED NOT NULL,
  staff_id BIGINT UNSIGNED NOT NULL,
  business_date DATE NOT NULL,
  bonus_type VARCHAR(20) NOT NULL DEFAULT 'PERFORMANCE',
  amount BIGINT NOT NULL,
  note VARCHAR(1000) NOT NULL,
  is_void TINYINT(1) NOT NULL DEFAULT 0,
  void_reason VARCHAR(1000) DEFAULT NULL,
  created_by_type VARCHAR(20) NOT NULL,
  created_by_id VARCHAR(64) NOT NULL,
  updated_by_type VARCHAR(20) DEFAULT NULL,
  updated_by_id VARCHAR(64) DEFAULT NULL,
  voided_by_type VARCHAR(20) DEFAULT NULL,
  voided_by_id VARCHAR(64) DEFAULT NULL,
  version INT NOT NULL DEFAULT 1,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (payroll_bonus_id),
  KEY idx_payroll_bonus_branch_date (branch_id, business_date DESC),
  KEY idx_payroll_bonus_staff_date (staff_id, business_date DESC),
  KEY idx_payroll_bonus_branch_staff (branch_id, staff_id),
  CONSTRAINT fk_payroll_bonus_branch FOREIGN KEY (branch_id) REFERENCES branches(branch_id),
  CONSTRAINT fk_payroll_bonus_staff FOREIGN KEY (staff_id) REFERENCES staff_users(staff_id),
  CONSTRAINT ck_payroll_bonus_type CHECK (bonus_type IN ('PERFORMANCE', 'ADJUSTMENT', 'OTHER')),
  CONSTRAINT ck_payroll_bonus_amount CHECK (amount > 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
